### ISSUE TITLE
上划bug

### ISSUE THREAD

**Issue by cyamz** [miluluyo/cute-cnblogs#20]
上划有时划不动，似乎是navList引起的，不确定是否只有我有这种情况。 https://www.cnblogs.com/cyamazing

**Comment by cyamz** [comment]
#9

**Comment by miluluyo** [comment]
文章有更新的 https://www.cnblogs.com/miluluyo/p/cute-cnblogs2.html

2021.03.10
博客园移动端页面上划时偶尔抖动问题已修复

https://blog-static.cnblogs.com/files/miluluyo/cute-cnblogs2.js 链接更改为 https://blog-static.cnblogs.com/files/miluluyo/cute-cnblogs3.js

**Comment by cyamz** [comment]
> 文章有更新的 https://www.cnblogs.com/miluluyo/p/cute-cnblogs2.html
> 
> 2021.03.10 博客园移动端页面上划时偶尔抖动问题已修复
> 
> https://blog-static.cnblogs.com/files/miluluyo/cute-cnblogs2.js 链接更改为 https://blog-static.cnblogs.com/files/miluluyo/cute-cnblogs3.js

感谢作者，主题超好看~
