### ISSUE TITLE
如何修改？

### ISSUE THREAD

**Issue by busyboxs** [miluluyo/cute-cnblogs#3]
你好。非常感谢分享该主题。
请问一下simpleMemory.min.js是在哪里加载的？
如果我想修改，修改之后应该放在哪里？
谢谢！

**Comment by miluluyo** [comment]
很抱歉现在才看到你的问题，simpleMemory是博客园其他人写的底层模版，是不能更改的，cute-cnblogs一期是基于此模版的。
