### ISSUE TITLE
手机端访问很卡

### ISSUE THREAD

**Issue by SimZhou** [miluluyo/cute-cnblogs#4]
rt
小米8
手机版chrome

**Comment by miluluyo** [comment]
原因已清，是看板娘猫导致的，可以用js判断下是PC端还是移动端，如果是移动端则不加载看板娘猫，这样就不卡了呢

**Comment by SimZhou** [comment]
哈，你不回复我我都快忘了。
你的博客真是可爱与美丽的炒鸡结合，不知道本人是不是也是这样的呢？^_^
博客已添加收藏夹~

**Comment by SimZhou** [comment]
嗯，现在貌似不卡了~
