### ISSUE TITLE
怎么设置自动播放音乐？

### ISSUE THREAD

**Issue by yoletPig** [miluluyo/cute-cnblogs#5]
ball ball 你们告诉我吧

**Comment by miluluyo** [comment]
在页首代码的最下面，加上
<script>
$(".aplayer-play").click()
</script>
就可以了 这个APlayer本身是有个属性的，autoplay，这个默认为false，就是不自动播放，但是这里的这个不知道什么原因，并没有起效，所以就使用JS叭
