### ISSUE TITLE
怎么设置整个body的那个灰色背景图

### ISSUE THREAD

**Issue by wkjCoder** [miluluyo/cute-cnblogs#7]
整个网页有一个灰色动漫女的背景图，那个怎么替换呢

**Comment by wenyuan** [comment]
`div#home::after` 中的 `background-image`。—— [参考文档](https://github.com/miluluyo/cute-cnblogs/blob/7d6e29a749e7c0216064f3b2b809b65fe343f25f/%E7%95%AA%E5%A4%96%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AF%87/README.md#%E5%8A%A8%E6%BC%AB%E4%BA%BA%E7%89%A9%E8%83%8C%E6%99%AF%E5%9B%BE%E7%89%87)
是问的这个么？

**Comment by wkjCoder** [comment]
是的，找到了，thank you！
