### ISSUE TITLE
鼠标滑轮往上滑时有时候屏幕会抖动

### ISSUE THREAD

**Issue by karlshuyuan** [miluluyo/cute-cnblogs#9]
同时
![image](https://user-images.githubusercontent.com/65219653/100537107-97cd5e80-3260-11eb-9847-b49822f321f8.png)
这一栏会闪烁
我有时候会出现这种情况, 有时候又正常

**Comment by karlshuyuan** [comment]
![image-20201130220451111](https://i.loli.net/2020/11/30/OjUTkmNow8CxPbJ.png)

**Comment by miluluyo** [comment]
PC端 向上滑动会出现 向下滑动会隐藏 移动端好像是有个屏幕抖动的问题 有空的时候我会定位一下问题并修正
